"""Add concise module documentation to Athena production source files.

This helper is used once to document responsibilities and architectural
boundaries without changing application behaviour.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DOCS: dict[str, str] = {
    "main.py": '''"""Application entry point for Athena.\n\nResponsibilities:\n- Build the platform collectors used by the command-line flow.\n- Instantiate the reusable import, merge and statistics services.\n- Coordinate collection without embedding platform-specific logic.\n- Convert collected values into normalized domain objects.\nArchitecture notes:\n- External access remains isolated in collector classes.\n- Business operations remain delegated to service classes.\n- Models carry normalized data between application layers.\n- Configuration values are read from the dedicated config module.\n- This module focuses on orchestration rather than business rules.\n"""\n\n''',
    "collectors/epic/epic_collector.py": '''"""Epic Games data collector used by Athena.\n\nResponsibilities:\n- Read Epic-related playtime information from the supported source.\n- Isolate platform-specific extraction from the rest of the application.\n- Convert raw values into the format expected by Athena services.\n- Report collection failures without leaking them into presentation code.\nArchitecture notes:\n- Platform details remain contained inside the collector layer.\n- Normalization is performed before data reaches higher-level services.\n- Debug helpers support diagnosis of difficult extraction cases.\n- The collector can evolve without changing the statistics layer.\n- Callers depend on its public collection contract, not its internals.\n"""\n\n''',
    "collectors/osu_collector.py": '''"""osu! API collector for Athena.\n\nResponsibilities:\n- Retrieve account and playtime information from the osu! service.\n- Encapsulate authentication and HTTP requests for this platform.\n- Validate remote responses before exposing values to the application.\n- Convert platform data into Athena-compatible domain information.\nArchitecture notes:\n- API-specific behaviour stays outside business and presentation layers.\n- Callers interact with the collector through a small public interface.\n- Authentication data is supplied through configuration at runtime.\n- Remote failures are handled at the integration boundary.\n- Normalized results can be reused by CLI and graphical workflows.\n"""\n\n''',
    "collectors/riot/lol_collector.py": '''"""League of Legends collector for Riot data.\n\nResponsibilities:\n- Retrieve match and account information required by Athena.\n- Estimate playtime from the available Riot match history.\n- Reuse the Riot cache repository instead of handling JSON directly.\n- Keep Riot-specific pagination and request rules inside this layer.\nArchitecture notes:\n- Persistent cache access is delegated to a repository object.\n- External API details do not leak into services or UI classes.\n- Collected values are prepared for normalized domain models.\n- Caching reduces unnecessary requests to the external API.\n- Errors are handled close to the external integration boundary.\n"""\n\n''',
    "collectors/riot/riot_base_collector.py": '''"""Shared foundation for Riot platform collectors.\n\nResponsibilities:\n- Centralize behaviour common to Riot-based integrations.\n- Provide reusable request and authentication helpers to subclasses.\n- Keep shared Riot configuration in one implementation boundary.\n- Reduce duplication between League of Legends and Valorant collectors.\nArchitecture notes:\n- Specialized collectors extend this base instead of copying logic.\n- Common integration rules therefore have a single maintenance point.\n- Platform-specific behaviour remains implemented by each subclass.\n- The class supports consistent error handling across Riot collectors.\n- Reuse at this layer improves maintainability of external integrations.\n"""\n\n''',
    "collectors/riot/valorant_collector.py": '''"""Valorant collector for Riot data used by Athena.\n\nResponsibilities:\n- Retrieve the Valorant information available to the application.\n- Encapsulate Riot-specific endpoints and response processing.\n- Convert remote records into values usable by Athena domain models.\n- Keep estimation rules close to the source that provides the data.\nArchitecture notes:\n- Shared Riot behaviour is inherited from the common base collector.\n- Business services do not depend on Riot response structures.\n- Remote failures remain isolated in the integration layer.\n- Returned information follows the same normalization approach as peers.\n- The collector can evolve independently of the graphical interface.\n"""\n\n''',
    "collectors/steam_collector.py": '''"""Steam API collector for the Athena application.\n\nResponsibilities:\n- Retrieve the owned-games information required by Athena.\n- Encapsulate Steam authentication and endpoint-specific parameters.\n- Validate the external response before returning collected records.\n- Expose playtime data without coupling callers to Steam JSON details.\nArchitecture notes:\n- Steam-specific integration logic remains inside this collector.\n- Normalized domain models are built outside raw API response handling.\n- The collector is reusable from both CLI and graphical workflows.\n- Configuration is provided at construction rather than hard-coded.\n- Failures at the external boundary are surfaced in a controlled way.\n"""\n\n''',
    "collectors/xbox/xbox_ui_collector.py": '''"""Xbox user-interface collector used by Athena.\n\nResponsibilities:\n- Extract Xbox playtime information from the supported UI workflow.\n- Isolate screen-driven collection from the rest of the application.\n- Transform extracted values into a predictable intermediate structure.\n- Keep UI automation concerns out of domain and statistics services.\nArchitecture notes:\n- Collection details remain replaceable behind the collector boundary.\n- OCR and screen interaction helpers are delegated to utility functions.\n- Higher layers receive data rather than automation implementation details.\n- Failures can be diagnosed without modifying business services.\n- The component complements API-based collectors with a separate source.\n"""\n\n''',
    "models/normalized_game.py": '''"""Canonical game model shared by Athena data sources.\n\nResponsibilities:\n- Represent a game using one structure regardless of its source platform.\n- Validate core invariants such as non-negative playtime and confidence.\n- Preserve optional source metadata required for later analysis.\n- Provide constructors that translate platform records into one model.\nArchitecture notes:\n- Steam, osu!, Riot and Xbox data converge on this domain object.\n- Services can therefore operate without platform-specific conditionals.\n- Factory class methods keep conversion rules close to the model contract.\n- ``to_dict`` provides a stable serialization shape for output layers.\n- The model is the main reusable boundary between collectors and services.\n"""\n\n''',
    "models/platform_account.py": '''"""Domain model describing an external gaming account.\n\nResponsibilities:\n- Store the identity and platform information needed for collection.\n- Provide platform-specific constructors behind one account abstraction.\n- Normalize identifiers before they are consumed by collectors or services.\n- Keep account metadata separate from individual game records.\nArchitecture notes:\n- Collectors receive a domain object instead of unrelated loose parameters.\n- Factory methods centralize conversion from platform account formats.\n- The model avoids duplicating account-shaping logic across workflows.\n- Optional fields support platforms with different identity requirements.\n- This object participates in the common normalized Athena data model.\n"""\n\n''',
    "models/sync_result.py": '''"""Domain model for the result of a synchronization operation.\n\nResponsibilities:\n- Describe whether a platform synchronization succeeded or failed.\n- Carry normalized game records produced during synchronization.\n- Preserve diagnostic information required by callers and the interface.\n- Offer a consistent result contract across different collectors.\nArchitecture notes:\n- Callers inspect one result type instead of platform-specific responses.\n- Error information travels as data rather than presentation-side logic.\n- The object simplifies coordination inside the import service.\n- Success and failure factories keep result construction consistent.\n- The model separates synchronization state from transport details.\n"""\n\n''',
    "models/user_profile.py": '''"""Domain model for an Athena user profile.\n\nResponsibilities:\n- Group profile-level information independently from platform collectors.\n- Provide a stable structure for persistence and application services.\n- Keep user metadata separate from individual normalized game records.\n- Support serialization through a small predictable model contract.\nArchitecture notes:\n- Repository code persists this model instead of UI-specific state.\n- Business services can depend on the model without knowing storage details.\n- The structure remains intentionally small and focused on profile data.\n- Future profile attributes can be added without changing collectors.\n- The model belongs to the domain layer of the Athena architecture.\n"""\n\n''',
    "repositories/profile_repository.py": '''"""Persistence repository for Athena user profiles.\n\nResponsibilities:\n- Centralize reading and writing of profile information.\n- Hide the concrete storage representation from application services.\n- Convert persisted values to and from the user-profile domain model.\n- Provide one persistence boundary for profile-related operations.\nArchitecture notes:\n- Callers do not manipulate profile files directly.\n- Storage changes remain localized to the repository implementation.\n- File-system details are kept outside collectors and presentation classes.\n- The repository supports separation between domain and persistence layers.\n- Explicit methods make persistence operations easier to test and replace.\n"""\n\n''',
    "repositories/riot_match_cache_repository.py": '''"""Repository dedicated to the Riot match cache.\n\nResponsibilities:\n- Read and write the cache used by Riot collectors.\n- Centralize JSON persistence and file-path handling for cached matches.\n- Expose account-level cache operations through explicit methods.\n- Prevent collectors from depending directly on the storage format.\nArchitecture notes:\n- ``LoLCollector`` consumes this repository through its public API.\n- Persistence details remain isolated from Riot collection logic.\n- A storage-format change is therefore concentrated in this component.\n- The repository provides a clear data-access boundary in Athena.\n- Cache reuse reduces repeated external API requests.\n"""\n\n''',
    "services/import_service.py": '''"""Application service coordinating imports from platform collectors.\n\nResponsibilities:\n- Execute collection through the collector contract supplied by callers.\n- Convert collected source data into normalized game records.\n- Return synchronization results using the common domain result model.\n- Keep import orchestration independent from UI and CLI presentation.\nArchitecture notes:\n- The same service is reused by command-line and graphical entry points.\n- Platform integrations remain delegated to collector implementations.\n- Business flow is centralized instead of duplicated between interfaces.\n- Normalized models form the boundary between collection and processing.\n- Errors are converted into a consistent application-level result.\n"""\n\n''',
    "services/merge_service.py": '''"""Application service responsible for merging normalized game records.\n\nResponsibilities:\n- Combine records coming from several supported gaming platforms.\n- Apply consistent duplicate-handling rules to normalized inputs.\n- Preserve useful source information while producing one merged collection.\n- Keep merge rules independent from collectors and presentation code.\nArchitecture notes:\n- The service works on ``NormalizedGame`` objects rather than raw APIs.\n- The same merge logic is reusable from CLI and graphical workflows.\n- Centralizing the rule avoids divergent behaviour between interfaces.\n- Platform-specific parsing is completed before this service is called.\n- The service forms part of Athena's reusable business core.\n"""\n\n''',
    "services/stats_service.py": '''"""Application service that computes statistics from normalized games.\n\nResponsibilities:\n- Aggregate playtime information from the normalized game collection.\n- Build summary indicators used by Athena presentation layers.\n- Group statistics by platform and other supported dimensions.\n- Keep calculation rules independent from interface widgets.\nArchitecture notes:\n- Inputs use domain models rather than external API response formats.\n- The service is shared by CLI and graphical application flows.\n- Calculation behaviour therefore has one implementation and one contract.\n- Presentation classes only display the values returned by this service.\n- The service forms part of Athena's reusable business core.\n"""\n\n''',
    "services/xbox_import_service.py": '''"""Application service dedicated to importing Xbox data.\n\nResponsibilities:\n- Convert Xbox import records into Athena normalized game objects.\n- Validate the imported structure before exposing it to higher layers.\n- Isolate Xbox file-import rules from UI and generic statistics code.\n- Return data compatible with the common merge and analysis pipeline.\nArchitecture notes:\n- Import-specific conversion is centralized in one service component.\n- Higher layers remain independent from the Xbox source file structure.\n- Normalized output can be processed with records from other platforms.\n- The service complements collectors when data originates from an import.\n- Changes to the Xbox import format remain localized here.\n"""\n\n''',
    "ui/app.py": '''"""Main graphical application window for Athena.\n\nResponsibilities:\n- Assemble views, collectors and reusable application services.\n- Coordinate user actions without reimplementing business calculations.\n- Maintain the current normalized games and summary state for the UI.\n- Route import results to the appropriate presentation components.\nArchitecture notes:\n- Import, merge and statistics services are reused from the business core.\n- Collectors remain responsible for external platform access.\n- Views focus on rendering and user interaction.\n- Domain models carry data between UI and service layers.\n- The class acts as presentation orchestration rather than business logic.\n"""\n\n''',
    "ui/home_view.py": '''"""Home view for the Athena graphical interface.\n\nResponsibilities:\n- Present the main entry actions available to the user.\n- Forward import requests to the callback supplied by the application.\n- Keep widget creation and layout inside the presentation layer.\n- Display introductory state without performing business calculations.\nArchitecture notes:\n- The view receives behaviour through callbacks instead of services internals.\n- Data collection remains outside this presentation component.\n- Styling choices are localized to the graphical layer.\n- The component can evolve without changing collector implementations.\n- Its public role is intentionally limited to presentation and interaction.\n"""\n\n''',
    "ui/library_view.py": '''"""Library view displaying normalized games in Athena.\n\nResponsibilities:\n- Render the merged collection of normalized game records.\n- Present platform and playtime information in a readable layout.\n- Refresh displayed content when application state changes.\n- Keep display formatting out of business and collection services.\nArchitecture notes:\n- The view consumes normalized models produced by the service layer.\n- It does not need to understand Steam, Riot, osu! or Xbox APIs.\n- Widget creation remains isolated in the presentation layer.\n- Data transformations required for business rules occur before rendering.\n- This separation allows presentation changes without collector changes.\n"""\n\n''',
    "ui/stats_view.py": '''"""Statistics view for the Athena graphical interface.\n\nResponsibilities:\n- Display summary values produced by the statistics service.\n- Render platform-level indicators using reusable UI widgets.\n- Refresh statistics when the current application summary changes.\n- Keep visual formatting separate from calculation rules.\nArchitecture notes:\n- Statistical calculations are completed by ``StatsService``.\n- The view only consumes the resulting summary structure.\n- Reusable cards and badges reduce duplicated presentation code.\n- No external platform API is accessed from this component.\n- The class belongs exclusively to the presentation layer.\n"""\n\n''',
    "ui/widgets/platform_badge.py": '''"""Reusable badge widget for displaying a gaming platform.\n\nResponsibilities:\n- Render a compact platform identifier inside Athena views.\n- Centralize the visual representation reused across presentation screens.\n- Keep platform badge styling out of higher-level view classes.\n- Provide one small widget with a focused presentation responsibility.\nArchitecture notes:\n- Reuse avoids duplicating layout and styling code between views.\n- The widget consumes already-normalized display values.\n- It contains no collection, persistence or business behaviour.\n- Changes to badge appearance remain isolated to this file.\n- The component follows the single-responsibility principle.\n"""\n\n''',
    "ui/widgets/stat_card.py": '''"""Reusable card widget for displaying a statistic.\n\nResponsibilities:\n- Present one label/value pair in a consistent visual component.\n- Centralize card styling shared by Athena statistics screens.\n- Reduce repeated widget construction in higher-level views.\n- Keep formatting concerns inside the presentation layer.\nArchitecture notes:\n- The widget receives computed values instead of calculating statistics.\n- Business rules remain delegated to ``StatsService``.\n- Reuse provides consistent rendering across the application.\n- Visual changes can be made without affecting domain services.\n- The component has a deliberately small presentation responsibility.\n"""\n\n''',
}


def has_module_docstring(source: str) -> bool:
    stripped = source.lstrip()
    return stripped.startswith('"""') or stripped.startswith("'''")


def main() -> None:
    changed = 0
    for relative_path, documentation in DOCS.items():
        path = ROOT / relative_path
        source = path.read_text(encoding="utf-8")
        if has_module_docstring(source):
            continue
        path.write_text(documentation + source, encoding="utf-8")
        changed += 1
        print(f"documented: {relative_path}")
    print(f"DOCUMENTED_FILES={changed}")


if __name__ == "__main__":
    main()
